// Code generated by "stringer -type=Type"; DO NOT EDIT.

package Blocks

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Air-0]
	_ = x[Stone-1]
	_ = x[Dirt-2]
	_ = x[Sand-3]
	_ = x[Grass-4]
	_ = x[Snow-5]
	_ = x[PalmLeaves-6]
	_ = x[PalmPlanks-7]
	_ = x[PalmLog-8]
	_ = x[_len-9]
}

const _Type_name = "AirStoneDirtSandGrassSnowPalmLeavesPalmPlanksPalmLog_len"

var _Type_index = [...]uint8{0, 3, 8, 12, 16, 21, 25, 35, 45, 52, 56}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
