// Code generated by "stringer -type=Type"; DO NOT EDIT.

package Blocks

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Air-0]
	_ = x[Dirt-1]
	_ = x[Grass-2]
	_ = x[PalmLeaves-3]
	_ = x[PalmPlanks-4]
	_ = x[PalmLog-5]
	_ = x[_len-6]
}

const _Type_name = "AirDirtGrassPalmLeavesPalmPlanksPalmLog_len"

var _Type_index = [...]uint8{0, 3, 7, 12, 22, 32, 39, 43}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
